package org.hzt.main;

import org.hzt.component.Header;
import org.hzt.component.Menu;
import org.hzt.form.Form1;
import org.hzt.form.Form2;
import org.hzt.form.Form3;
import org.hzt.form.FormHome;
import org.hzt.swing.PanelBorder;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;

import static javax.swing.GroupLayout.DEFAULT_SIZE;

public final class Main extends JFrame {

    /**
     * Creates new form Main
     */
    private final FormHome home;
    private final Form1 form1;
    private final Form2 form2;
    private final Form3 form3;

    private JPanel mainPanel;
    private Menu menu;

    public Main() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        home = new FormHome();
        form1 = new Form1();
        form2 = new Form2();
        form3 = new Form3();
        menu.initMoving(Main.this);
        menu.addEventMenuSelected(index -> {
            switch (index) {
                case 0 -> setForm(home);
                case 1 -> setForm(form1);
                case 2 -> setForm(form2);
                case 3 -> setForm(form3);
            }
        });
        //  set when system open start with home form
        setForm(new FormHome());
    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        PanelBorder panelBorder1 = new PanelBorder();
        menu = new Menu();
        Header header2 = new Header();
        mainPanel = new JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(242, 242, 242));

        header2.setFont(new java.awt.Font("sansserif", Font.PLAIN, 14));

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
                panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(header2, DEFAULT_SIZE, 965, Short.MAX_VALUE)
                                        .addGroup(panelBorder1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(mainPanel, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())))
        );
        panelBorder1Layout.setVerticalGroup(
                panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menu, DEFAULT_SIZE, 657, Short.MAX_VALUE)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainPanel, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBorder1, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBorder1, DEFAULT_SIZE, DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        final var nimbus = "Nimbus";
        try {
            final var info = Arrays.stream(UIManager.getInstalledLookAndFeels())
                    .filter(i -> nimbus.equals(i.getName()))
                    .findFirst()
                    .orElseThrow(() -> new UnsupportedLookAndFeelException(nimbus + " not found"));
            UIManager.setLookAndFeel(info.getClassName());
        } catch (ClassNotFoundException |
                 InstantiationException |
                 IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            LoggerFactory.getLogger(Main.class.getName()).error("Could not load look and feel " + nimbus, ex);
        }
        EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

}
